export const API_ENDPOINTS = {
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  FORGET_PASSWORD: '/forget-password',
  CATEGORIES: '/categories.json',
  CATEGORIES_2: '/categories.json',
  FEATURED_CATEGORIES: '/featured_categories.json',
  COLLECTIONS: '/collections.json',
  BRANDS: '/brands.json',
  PRODUCTS: '/products.json',
  PRODUCTS_2: '/products_2.json',
  FEATURED_PRODUCTS: '/featured_products.json',
  TOP_SELLER_PRODUCTS: '/products_top_seller.json',
  ON_SELLING_PRODUCTS: '/products_on_selling.json',
  PRODUCT: '/product.json',
  ELECTRONIC_PRODUCTS:'/products_electronic.json',
  ELECTRONIC_CATEGORY: '/category_electronic.json',
  CLOTH_CATEGORY: '/category_cloth.json',
  FASHION_PRODUCTS: '/products_fashion.json',
  RELATED_PRODUCTS: '/related_products.json',
  BEST_SELLER_PRODUCTS: '/products_best_seller.json',
  NEW_ARRIVAL_PRODUCTS: '/products_new_arrival.json',
  FLASH_SALE_PRODUCTS: '/products_flash_sale.json',
  POPULAR_PRODUCTS: '/products_popular.json',
  NEW_ARRIVAL_PRODUCTS_ANCIENT: '/products_new_arrival.json',
  PRODUCTS_ANCIENT: '/products_ancient.json',
  FLASH_SALE_PRODUCTS_ANCIENT: '/products_flash_sale_ancient.json',
  FEATURED_PRODUCTS_ANCIENT: '/featured_products_ancient.json',
  CATEGORIES_ANCIENT: '/categories_ancient.json',
  BRANDS_ANCIENT: '/brands_ancient.json',

  SHOPS: '/shops.json',
  SHOP: '/shop.json',
  BLOGS: '/blog.json',

  SEARCH: '/search.json',
  ORDERS: '/orders.json',
  ORDER: '/order.json',
}
