export const LIMITS = {
  CATEGORIES_LIMITS: 6,
  PRODUCTS_LIMITS: 20,
  RELATED_PRODUCTS_LIMITS: 15,
  BEST_SELLER_PRODUCTS_LIMITS: 15,
  BEST_SELLER_HOME2_PRODUCTS_LIMITS: 6,
  NEW_ARRIVAL_PRODUCTS_LIMITS: 6,
 // POPULAR_PRODUCTS_LIMITS: 14,

  TOP_SELLER_PRODUCTS: 14,
  POPULAR_PRODUCTS_TWO_LIMITS: 4,
  FASHION_PRODUCTS_LIMITS: 15,
  ELECTRONIC_PRODUCTS_LIMITS: 15,
};
