// all api end points changed from "/_____.json" to "api/____.json"  

export const API_ENDPOINTS = {
  LOGIN: 'api/login',  // changed from "/login"
  REGISTER: 'api/register',
  LOGOUT: 'api/logout',
  FORGET_PASSWORD: 'api/forget-password',
  CATEGORIES: 'api/categories.json',
  DIETARY: 'api/dietary.json',
  BRANDS: 'api/brands.json',
  PRODUCTS: 'api/products.json',
  PRODUCT: 'api/product.json',
  RELATED_PRODUCTS: 'api/related_products.json',
  BEST_SELLER_PRODUCTS: 'api/products_best_seller.json', 
  NEW_ARRIVAL_PRODUCTS: 'api/products_new_arrival.json',
  POPULAR_PRODUCTS: 'api/products_popular.json',
  COOKIES_PRODUCTS: 'api/products_cookies.json',
  CHIPS_PRODUCTS: 'api/products_chips.json',
  ELECTRONIC_CATEGORY: 'api/category_electronic.json',
  CLOTH_CATEGORY: 'api/category_cloth.json',
  FASHION_PRODUCTS: 'api/products_fashion.json',
  ELETRONIC_PRODUCTS: 'api/products_electronic.json',
  SEARCH: 'api/search.json',
  ORDERS: 'api/orders.json',
  ORDER: 'api/order.json',
  ORDER_STATUS: 'api/order-status.json',
  ADDRESS: 'api/address.json',
  PAYMENT: 'api/payment.json',
  CONTACT: 'api/contact.json',
  SHOP: 'api/shop.json',
  SHOPS: 'api/shops.json',
  WISHLIST: 'api/wishlist.json',
  BLOGS: 'api/blog.json',
  BLOGDETAILS: 'api/blogDetails.json',
};
